-- Monitor data table for /monitor-list.
-- Run this in Supabase SQL Editor before inserting monitor products.

BEGIN;

CREATE TABLE IF NOT EXISTS am_monitor_data (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  brand text,
  name text NOT NULL,
  size_inch numeric,
  resolution text,
  refresh_rate_hz integer,
  panel_type text,
  has_usb_c boolean DEFAULT false,
  usb_c_power_delivery_w integer,
  price integer,
  real_price integer,
  url text,
  af_url text,
  img_url text,
  fetched_at date DEFAULT CURRENT_DATE,
  is_active boolean DEFAULT true
);

CREATE INDEX IF NOT EXISTS idx_am_monitor_data_active_price
  ON am_monitor_data (is_active, real_price, price);

CREATE INDEX IF NOT EXISTS idx_am_monitor_data_size_refresh
  ON am_monitor_data (size_inch, refresh_rate_hz);

COMMIT;
