-- Specsy tablet product INSERT SQL generated on 2026-06-21
-- Run scripts/create-tablet-data-table.sql first.
-- Review candidates before running this in Supabase SQL Editor.
BEGIN;

INSERT INTO am_tablet_data (asin, brand, name, series, os_family, os_version, soc, soc_score, ram_gb, rom_gb, display_size_inch, resolution, refresh_rate_hz, battery_life_hours, battery_capacity_mah, weight_g, has_cellular, price, real_price, url, af_url, img_url, fetched_at, is_active)
SELECT 'B0DZ7WF87P', 'Apple(アップル)', 'Apple 11 インチ iPad (A16): 11 インチモデル、Liquid Retina ディスプレイ、128GB、Wi-Fi 6、12MP フロント/12MP バックカメラ、Touch ID、一日中使えるバ ッテリー - シルバー', NULL, 'ipad', NULL, 'Apple A16', 25, NULL, 128, 11.0, NULL, NULL, NULL, NULL, NULL, false, 56364, 56364, 'https://www.amazon.co.jp/dp/B0DZ7WF87P', 'https://www.amazon.co.jp/dp/B0DZ7WF87P?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/31-NvY2Tw8L._SL160_.jpg', '2026-06-21', true
WHERE NOT EXISTS (SELECT 1 FROM am_tablet_data WHERE asin = 'B0DZ7WF87P' OR (url ILIKE '%B0DZ7WF87P%' OR af_url ILIKE '%B0DZ7WF87P%'));
INSERT INTO am_tablet_data (asin, brand, name, series, os_family, os_version, soc, soc_score, ram_gb, rom_gb, display_size_inch, resolution, refresh_rate_hz, battery_life_hours, battery_capacity_mah, weight_g, has_cellular, price, real_price, url, af_url, img_url, fetched_at, is_active)
SELECT 'B0DZ8HV6RT', 'Apple(アップル)', 'Apple 11 インチ iPad (A16): 11 インチモデル、Liquid Retina ディスプレイ、128GB、Wi-Fi 6、12MP フロント/12MP バックカメラ、Touch ID、一日中使えるバ ッテリー - イエロー', NULL, 'ipad', NULL, 'Apple A16', 25, NULL, 128, 11.0, NULL, NULL, NULL, NULL, NULL, false, 58315, 58315, 'https://www.amazon.co.jp/dp/B0DZ8HV6RT', 'https://www.amazon.co.jp/dp/B0DZ8HV6RT?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/31IEsDN7eFL._SL160_.jpg', '2026-06-21', true
WHERE NOT EXISTS (SELECT 1 FROM am_tablet_data WHERE asin = 'B0DZ8HV6RT' OR (url ILIKE '%B0DZ8HV6RT%' OR af_url ILIKE '%B0DZ8HV6RT%'));
INSERT INTO am_tablet_data (asin, brand, name, series, os_family, os_version, soc, soc_score, ram_gb, rom_gb, display_size_inch, resolution, refresh_rate_hz, battery_life_hours, battery_capacity_mah, weight_g, has_cellular, price, real_price, url, af_url, img_url, fetched_at, is_active)
SELECT 'B0DZ8J8TR2', 'Apple(アップル)', 'Apple 11 インチ iPad (A16): 11 インチモデル、Liquid Retina ディスプレイ、128GB、Wi-Fi 6、12MP フロント/12MP バックカメラ、Touch ID、一日中使えるバ ッテリー - ピンク', NULL, 'ipad', NULL, 'Apple A16', 25, NULL, 128, 11.0, NULL, NULL, NULL, NULL, NULL, false, 56364, 56364, 'https://www.amazon.co.jp/dp/B0DZ8J8TR2', 'https://www.amazon.co.jp/dp/B0DZ8J8TR2?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/31Bnc9Z27HL._SL160_.jpg', '2026-06-21', true
WHERE NOT EXISTS (SELECT 1 FROM am_tablet_data WHERE asin = 'B0DZ8J8TR2' OR (url ILIKE '%B0DZ8J8TR2%' OR af_url ILIKE '%B0DZ8J8TR2%'));
INSERT INTO am_tablet_data (asin, brand, name, series, os_family, os_version, soc, soc_score, ram_gb, rom_gb, display_size_inch, resolution, refresh_rate_hz, battery_life_hours, battery_capacity_mah, weight_g, has_cellular, price, real_price, url, af_url, img_url, fetched_at, is_active)
SELECT 'B0GQW8NNNS', 'Apple(アップル)', 'Apple 11インチiPad Air（M4）：Liquid Retinaディスプレイ、128GB、12MPフロント/バックカメラ、Apple N1によるWi-Fi 7 + 5Gモバイル通信、Touch ID、一日中使えるバッテリー — パープル', NULL, 'ipad', NULL, 'Apple M4', 35, NULL, 128, 11.0, NULL, NULL, NULL, NULL, NULL, true, 124800, 124800, 'https://www.amazon.co.jp/dp/B0GQW8NNNS', 'https://www.amazon.co.jp/dp/B0GQW8NNNS?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/31nIxB6F9SL._SL160_.jpg', '2026-06-21', true
WHERE NOT EXISTS (SELECT 1 FROM am_tablet_data WHERE asin = 'B0GQW8NNNS' OR (url ILIKE '%B0GQW8NNNS%' OR af_url ILIKE '%B0GQW8NNNS%'));
INSERT INTO am_tablet_data (asin, brand, name, series, os_family, os_version, soc, soc_score, ram_gb, rom_gb, display_size_inch, resolution, refresh_rate_hz, battery_life_hours, battery_capacity_mah, weight_g, has_cellular, price, real_price, url, af_url, img_url, fetched_at, is_active)
SELECT 'B0DZ84FKKP', 'Apple(アップル)', 'Apple 11 インチ iPad Air (M3): Apple Intelligence のために設計、Liquid Retina ディスプレイ、128GB、12MP フロント/バックカメラ、Wi-Fi 6E + 5G 携帯電話通信、 Touch ID、一日中使えるバッテリー', NULL, 'ipad', NULL, 'Apple M3', 33, NULL, 128, 11.0, NULL, NULL, NULL, NULL, NULL, true, 124801, 124801, 'https://www.amazon.co.jp/dp/B0DZ84FKKP', 'https://www.amazon.co.jp/dp/B0DZ84FKKP?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/41bhaBvB3HL._SL160_.jpg', '2026-06-21', true
WHERE NOT EXISTS (SELECT 1 FROM am_tablet_data WHERE asin = 'B0DZ84FKKP' OR (url ILIKE '%B0DZ84FKKP%' OR af_url ILIKE '%B0DZ84FKKP%'));
INSERT INTO am_tablet_data (asin, brand, name, series, os_family, os_version, soc, soc_score, ram_gb, rom_gb, display_size_inch, resolution, refresh_rate_hz, battery_life_hours, battery_capacity_mah, weight_g, has_cellular, price, real_price, url, af_url, img_url, fetched_at, is_active)
SELECT 'B0F9P1B6R4', 'xiaomi(シャオミ)', 'シャオミ(Xiaomi) タブレット Redmi Pad 2 4GB+128GB ラベンダーパープル wi-fiモデル 2.5K 大型11インチディスプレ Dolby Atmos対応 9000mAh 大容量 バッテリー 高性能チップHelio G100-Ultra 2TBまでmi', NULL, 'android', NULL, 'Helio G100', 16, 4, 128, 11.0, NULL, 90, NULL, 9000, NULL, false, 27980, 27980, 'https://www.amazon.co.jp/dp/B0F9P1B6R4', 'https://www.amazon.co.jp/dp/B0F9P1B6R4?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/31pitl88hiL._SL160_.jpg', '2026-06-21', true
WHERE NOT EXISTS (SELECT 1 FROM am_tablet_data WHERE asin = 'B0F9P1B6R4' OR (url ILIKE '%B0F9P1B6R4%' OR af_url ILIKE '%B0F9P1B6R4%'));
INSERT INTO am_tablet_data (asin, brand, name, series, os_family, os_version, soc, soc_score, ram_gb, rom_gb, display_size_inch, resolution, refresh_rate_hz, battery_life_hours, battery_capacity_mah, weight_g, has_cellular, price, real_price, url, af_url, img_url, fetched_at, is_active)
SELECT 'B0GQWSBMQ1', 'Apple(アップル)', 'Apple 11インチiPad Air（M4）：Liquid Retinaディスプレイ、128GB、12MPフロント/バックカメラ、Apple N1によるWi-Fi 7、Touch ID、一日中使えるバッテリー — ブルー', NULL, 'ipad', NULL, 'Apple M4', 35, NULL, 128, 11.0, NULL, NULL, NULL, NULL, NULL, false, 98800, 98800, 'https://www.amazon.co.jp/dp/B0GQWSBMQ1', 'https://www.amazon.co.jp/dp/B0GQWSBMQ1?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/41H7ZQJcV8L._SL160_.jpg', '2026-06-21', true
WHERE NOT EXISTS (SELECT 1 FROM am_tablet_data WHERE asin = 'B0GQWSBMQ1' OR (url ILIKE '%B0GQWSBMQ1%' OR af_url ILIKE '%B0GQWSBMQ1%'));
INSERT INTO am_tablet_data (asin, brand, name, series, os_family, os_version, soc, soc_score, ram_gb, rom_gb, display_size_inch, resolution, refresh_rate_hz, battery_life_hours, battery_capacity_mah, weight_g, has_cellular, price, real_price, url, af_url, img_url, fetched_at, is_active)
SELECT 'B0GQW2J67Z', 'Apple(アップル)', 'Apple 11インチiPad Air（M4）：Liquid Retinaディスプレイ、256GB、12MPフロント/バックカメラ、Apple N1によるWi-Fi 7、Touch ID、一日中使えるバッテリー — スターライト', NULL, 'ipad', NULL, 'Apple M4', 35, NULL, 256, 11.0, NULL, NULL, NULL, NULL, NULL, false, 109899, 109899, 'https://www.amazon.co.jp/dp/B0GQW2J67Z', 'https://www.amazon.co.jp/dp/B0GQW2J67Z?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/31wZmPlbT8L._SL160_.jpg', '2026-06-21', true
WHERE NOT EXISTS (SELECT 1 FROM am_tablet_data WHERE asin = 'B0GQW2J67Z' OR (url ILIKE '%B0GQW2J67Z%' OR af_url ILIKE '%B0GQW2J67Z%'));
INSERT INTO am_tablet_data (asin, brand, name, series, os_family, os_version, soc, soc_score, ram_gb, rom_gb, display_size_inch, resolution, refresh_rate_hz, battery_life_hours, battery_capacity_mah, weight_g, has_cellular, price, real_price, url, af_url, img_url, fetched_at, is_active)
SELECT 'B0GQWKSTGS', 'Apple(アップル)', 'Apple 11インチiPad Air（M4）：Liquid Retinaディスプレイ、512GB、12MPフロント/バックカメラ、Apple N1によるWi-Fi 7、Touch ID、一日中使えるバッテリー — スペースグレイ', NULL, 'ipad', NULL, 'Apple M4', 35, NULL, 512, 11.0, NULL, NULL, NULL, NULL, NULL, false, 150800, 150800, 'https://www.amazon.co.jp/dp/B0GQWKSTGS', 'https://www.amazon.co.jp/dp/B0GQWKSTGS?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/31-70FGPFZL._SL160_.jpg', '2026-06-21', true
WHERE NOT EXISTS (SELECT 1 FROM am_tablet_data WHERE asin = 'B0GQWKSTGS' OR (url ILIKE '%B0GQWKSTGS%' OR af_url ILIKE '%B0GQWKSTGS%'));
INSERT INTO am_tablet_data (asin, brand, name, series, os_family, os_version, soc, soc_score, ram_gb, rom_gb, display_size_inch, resolution, refresh_rate_hz, battery_life_hours, battery_capacity_mah, weight_g, has_cellular, price, real_price, url, af_url, img_url, fetched_at, is_active)
SELECT 'B0DK467P86', 'Apple(アップル)', 'Apple iPad mini(A17 Pro):Apple Intelligence、8.3 インチ Liquid Retina ディスプレ イ、128GB、Wi-Fi 6E、12MP フロントカメラ/12MP バックカメ ラ、Touch ID、一日中使えるバッテリー ‒ スペ', NULL, 'ipad', NULL, 'Apple A17 Pro', 29, NULL, 128, 8.3, NULL, NULL, NULL, NULL, NULL, false, 78800, 78800, 'https://www.amazon.co.jp/dp/B0DK467P86', 'https://www.amazon.co.jp/dp/B0DK467P86?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/41iAvd7sXvL._SL160_.jpg', '2026-06-21', true
WHERE NOT EXISTS (SELECT 1 FROM am_tablet_data WHERE asin = 'B0DK467P86' OR (url ILIKE '%B0DK467P86%' OR af_url ILIKE '%B0DK467P86%'));
INSERT INTO am_tablet_data (asin, brand, name, series, os_family, os_version, soc, soc_score, ram_gb, rom_gb, display_size_inch, resolution, refresh_rate_hz, battery_life_hours, battery_capacity_mah, weight_g, has_cellular, price, real_price, url, af_url, img_url, fetched_at, is_active)
SELECT 'B0DK43L4K3', 'Apple(アップル)', 'Apple iPad mini(A17 Pro):Apple Intelligence、8.3 インチ Liquid Retina ディスプレ イ、128GB、Wi-Fi 6E、12MP フロントカメラ/12MP バックカメ ラ、Touch ID、一日中使えるバッテリー ‒ パー', NULL, 'ipad', NULL, 'Apple A17 Pro', 29, NULL, 128, 8.3, NULL, NULL, NULL, NULL, NULL, false, 78149, 78149, 'https://www.amazon.co.jp/dp/B0DK43L4K3', 'https://www.amazon.co.jp/dp/B0DK43L4K3?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/4109BLfIzJL._SL160_.jpg', '2026-06-21', true
WHERE NOT EXISTS (SELECT 1 FROM am_tablet_data WHERE asin = 'B0DK43L4K3' OR (url ILIKE '%B0DK43L4K3%' OR af_url ILIKE '%B0DK43L4K3%'));
INSERT INTO am_tablet_data (asin, brand, name, series, os_family, os_version, soc, soc_score, ram_gb, rom_gb, display_size_inch, resolution, refresh_rate_hz, battery_life_hours, battery_capacity_mah, weight_g, has_cellular, price, real_price, url, af_url, img_url, fetched_at, is_active)
SELECT 'B0DK44CJ9K', 'Apple(アップル)', 'Apple iPad mini(A17 Pro):Apple Intelligence、8.3 インチ Liquid Retina ディスプレ イ、128GB、Wi-Fi 6E、12MP フロントカメラ/12MP バックカメ ラ、Touch ID、一日中使えるバッテリー ‒ ブル', NULL, 'ipad', NULL, 'Apple A17 Pro', 29, NULL, 128, 8.3, NULL, NULL, NULL, NULL, NULL, false, 78149, 78149, 'https://www.amazon.co.jp/dp/B0DK44CJ9K', 'https://www.amazon.co.jp/dp/B0DK44CJ9K?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/41OlI610oHL._SL160_.jpg', '2026-06-21', true
WHERE NOT EXISTS (SELECT 1 FROM am_tablet_data WHERE asin = 'B0DK44CJ9K' OR (url ILIKE '%B0DK44CJ9K%' OR af_url ILIKE '%B0DK44CJ9K%'));
INSERT INTO am_tablet_data (asin, brand, name, series, os_family, os_version, soc, soc_score, ram_gb, rom_gb, display_size_inch, resolution, refresh_rate_hz, battery_life_hours, battery_capacity_mah, weight_g, has_cellular, price, real_price, url, af_url, img_url, fetched_at, is_active)
SELECT 'B0F9P19S1B', 'xiaomi(シャオミ)', 'シャオミ(Xiaomi) タブレット Redmi Pad 2 4GB+128GB ミントグリーン wi-fiモデル 2.5K 大型11インチディスプレ Dolby Atmos対応 9000mAh 大容量 バッテリー 高性能チップHelio G100-Ultra 2TBまでmicr', NULL, 'android', NULL, 'Helio G100', 16, 4, 128, 11.0, NULL, 90, NULL, 9000, NULL, false, 27980, 27980, 'https://www.amazon.co.jp/dp/B0F9P19S1B', 'https://www.amazon.co.jp/dp/B0F9P19S1B?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/31QciORm9uL._SL160_.jpg', '2026-06-21', true
WHERE NOT EXISTS (SELECT 1 FROM am_tablet_data WHERE asin = 'B0F9P19S1B' OR (url ILIKE '%B0F9P19S1B%' OR af_url ILIKE '%B0F9P19S1B%'));
INSERT INTO am_tablet_data (asin, brand, name, series, os_family, os_version, soc, soc_score, ram_gb, rom_gb, display_size_inch, resolution, refresh_rate_hz, battery_life_hours, battery_capacity_mah, weight_g, has_cellular, price, real_price, url, af_url, img_url, fetched_at, is_active)
SELECT 'B0D2K5YP66', 'ALLDOCUBE', 'ALLDOCUBE iPlay60 mini Pro 8.4インチタブレット Android15 顔認証 4GLTE デュアルスピーカー 6軸ジャイロ HelioG99 16GB+128GB+512GB拡張 1920×1200FHD WidevineL1 6050mAh PD18', NULL, 'android', '15', 'Helio G99', 15, 16, 128, 8.4, '1920x1200', NULL, NULL, 6050, NULL, true, 22999, 22999, 'https://www.amazon.co.jp/dp/B0D2K5YP66', 'https://www.amazon.co.jp/dp/B0D2K5YP66?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/51d+Yxif4DL._SL160_.jpg', '2026-06-21', true
WHERE NOT EXISTS (SELECT 1 FROM am_tablet_data WHERE asin = 'B0D2K5YP66' OR (url ILIKE '%B0D2K5YP66%' OR af_url ILIKE '%B0D2K5YP66%'));
INSERT INTO am_tablet_data (asin, brand, name, series, os_family, os_version, soc, soc_score, ram_gb, rom_gb, display_size_inch, resolution, refresh_rate_hz, battery_life_hours, battery_capacity_mah, weight_g, has_cellular, price, real_price, url, af_url, img_url, fetched_at, is_active)
SELECT 'B0F4JR2QDK', 'ALLDOCUBE', 'ALLDOCUBE iPlay 70 mini Pro タブレット8.4インチ MediaTek Dimensity MT8791 タブレット Android 15 90Hz高リフレッシュレート 4GLTE 1920×1200解像度 16GB+128GB 6050mAh PD18', NULL, 'android', '15', 'Helio G99', 15, 8, 128, 8.4, '1920x1200', 90, 15, 6050, NULL, true, 28999, 28999, 'https://www.amazon.co.jp/dp/B0F4JR2QDK', 'https://www.amazon.co.jp/dp/B0F4JR2QDK?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/51Lj1xxwbgL._SL160_.jpg', '2026-06-21', true
WHERE NOT EXISTS (SELECT 1 FROM am_tablet_data WHERE asin = 'B0F4JR2QDK' OR (url ILIKE '%B0F4JR2QDK%' OR af_url ILIKE '%B0F4JR2QDK%'));
INSERT INTO am_tablet_data (asin, brand, name, series, os_family, os_version, soc, soc_score, ram_gb, rom_gb, display_size_inch, resolution, refresh_rate_hz, battery_life_hours, battery_capacity_mah, weight_g, has_cellular, price, real_price, url, af_url, img_url, fetched_at, is_active)
SELECT 'B0D2K2F5PK', 'ALLDOCUBE', 'ALLDOCUBE iPlay60mini Pro 8.4インチタブレット 顔認識 4GLTE デュアルスピーカー WidevineL1 Android15タブレット 6軸ジャイロ 1920×1200FHDディスプレイ 16GB(8+8仮想) +128GB+512GB拡張 605', NULL, 'android', '15', 'Helio G99', 15, 8, 128, 8.4, '1920x1200', NULL, NULL, 6050, NULL, true, 22999, 22999, 'https://www.amazon.co.jp/dp/B0D2K2F5PK', 'https://www.amazon.co.jp/dp/B0D2K2F5PK?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/51PbK4WpOkL._SL160_.jpg', '2026-06-21', true
WHERE NOT EXISTS (SELECT 1 FROM am_tablet_data WHERE asin = 'B0D2K2F5PK' OR (url ILIKE '%B0D2K2F5PK%' OR af_url ILIKE '%B0D2K2F5PK%'));
INSERT INTO am_tablet_data (asin, brand, name, series, os_family, os_version, soc, soc_score, ram_gb, rom_gb, display_size_inch, resolution, refresh_rate_hz, battery_life_hours, battery_capacity_mah, weight_g, has_cellular, price, real_price, url, af_url, img_url, fetched_at, is_active)
SELECT 'B0G338K9WJ', 'Headwolf', 'Headwolf タブレット ８インチ Android 15 SIMフリー - FPad7 tablet MT8791T 2560x1600解像度 16(8+8拡張)GB LPDDR5 256GB UFS 3.1 6軸ジャイロ 6500mAh PD18W急速充電 4G通信 WiF', NULL, 'android', '15', 'Dimensity 7050', 20, 8, 256, 8.0, '2560x1600', NULL, 8, 6500, NULL, true, 26996, 26996, 'https://www.amazon.co.jp/dp/B0G338K9WJ', 'https://www.amazon.co.jp/dp/B0G338K9WJ?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/51i74NOAmHL._SL160_.jpg', '2026-06-21', true
WHERE NOT EXISTS (SELECT 1 FROM am_tablet_data WHERE asin = 'B0G338K9WJ' OR (url ILIKE '%B0G338K9WJ%' OR af_url ILIKE '%B0G338K9WJ%'));
INSERT INTO am_tablet_data (asin, brand, name, series, os_family, os_version, soc, soc_score, ram_gb, rom_gb, display_size_inch, resolution, refresh_rate_hz, battery_life_hours, battery_capacity_mah, weight_g, has_cellular, price, real_price, url, af_url, img_url, fetched_at, is_active)
SELECT 'B09FKYRD22', 'TECLAST', 'TECLAST P50 タブレット11インチ wi-fiモデル Android 16GB+128GB+1TB拡張 アンドロイド 14 タブレット 11インチ 90Hz 1280*800 IPS 大画面+8000mAh+Widevine L1+8コアCPU T606 +BT5.0+', NULL, 'android', '16', 'Unisoc T606', 8, 10, 128, 11.0, '1280x800', 90, 11, 8000, NULL, false, 19932, 19932, 'https://www.amazon.co.jp/dp/B09FKYRD22', 'https://www.amazon.co.jp/dp/B09FKYRD22?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/51HaX0zGLYL._SL160_.jpg', '2026-06-21', true
WHERE NOT EXISTS (SELECT 1 FROM am_tablet_data WHERE asin = 'B09FKYRD22' OR (url ILIKE '%B09FKYRD22%' OR af_url ILIKE '%B09FKYRD22%'));
INSERT INTO am_tablet_data (asin, brand, name, series, os_family, os_version, soc, soc_score, ram_gb, rom_gb, display_size_inch, resolution, refresh_rate_hz, battery_life_hours, battery_capacity_mah, weight_g, has_cellular, price, real_price, url, af_url, img_url, fetched_at, is_active)
SELECT 'B0F9NM1GZJ', 'BekoQurd', 'BekoQurd M11 タブレット 11インチ Android、12GB RAM 128GB ROM、Helio G99 プロセッサ、90Hz IPS液晶、8100mAhバッテリー、4スピーカー、Widevine L1認証、GMS認証、20W急速充電、仕事 ゲーム 動画視聴に最', NULL, 'android', NULL, 'Helio G99', 15, 12, 128, 11.0, '1920x1200', 90, NULL, 8100, 513, false, 18999, 18999, 'https://www.amazon.co.jp/dp/B0F9NM1GZJ', 'https://www.amazon.co.jp/dp/B0F9NM1GZJ?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/419HKA5vY6L._SL160_.jpg', '2026-06-21', true
WHERE NOT EXISTS (SELECT 1 FROM am_tablet_data WHERE asin = 'B0F9NM1GZJ' OR (url ILIKE '%B0F9NM1GZJ%' OR af_url ILIKE '%B0F9NM1GZJ%'));
INSERT INTO am_tablet_data (asin, brand, name, series, os_family, os_version, soc, soc_score, ram_gb, rom_gb, display_size_inch, resolution, refresh_rate_hz, battery_life_hours, battery_capacity_mah, weight_g, has_cellular, price, real_price, url, af_url, img_url, fetched_at, is_active)
SELECT 'B0GJ3S68KD', 'Headwolf', 'Android 16 タブレット 11インチ Wi-Fiモデル Headwolf WPad7、In-Cell 1920x1200 FHD、8000mAh、8コアCPU T615、24GB(4+20拡張)RAM+128GB ROM、Widevine L1対応、5MP/13MP、2.', NULL, 'android', '16', 'Unisoc T615', 9, 20, 128, 11.0, '1920x1200', NULL, NULL, 8000, 619, false, 17999, 17999, 'https://www.amazon.co.jp/dp/B0GJ3S68KD', 'https://www.amazon.co.jp/dp/B0GJ3S68KD?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/51VM55VqFpL._SL160_.jpg', '2026-06-21', true
WHERE NOT EXISTS (SELECT 1 FROM am_tablet_data WHERE asin = 'B0GJ3S68KD' OR (url ILIKE '%B0GJ3S68KD%' OR af_url ILIKE '%B0GJ3S68KD%'));
INSERT INTO am_tablet_data (asin, brand, name, series, os_family, os_version, soc, soc_score, ram_gb, rom_gb, display_size_inch, resolution, refresh_rate_hz, battery_life_hours, battery_capacity_mah, weight_g, has_cellular, price, real_price, url, af_url, img_url, fetched_at, is_active)
SELECT 'B0D8VM6G33', 'Lenovo', 'Lenovo Tablet M11、11インチ WUXGA (1920x1200) IPS、指紋防止、タッチスクリーン、4GB、128GB eMMC、Android 13 Tab Pen', NULL, 'android', '13', 'Helio G88', 11, 4, 128, 11.0, '1920x1200', NULL, NULL, NULL, NULL, false, 72201, 72201, 'https://www.amazon.co.jp/dp/B0D8VM6G33', 'https://www.amazon.co.jp/dp/B0D8VM6G33?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/413nu1EKx9L._SL160_.jpg', '2026-06-21', true
WHERE NOT EXISTS (SELECT 1 FROM am_tablet_data WHERE asin = 'B0D8VM6G33' OR (url ILIKE '%B0D8VM6G33%' OR af_url ILIKE '%B0D8VM6G33%'));
INSERT INTO am_tablet_data (asin, brand, name, series, os_family, os_version, soc, soc_score, ram_gb, rom_gb, display_size_inch, resolution, refresh_rate_hz, battery_life_hours, battery_capacity_mah, weight_g, has_cellular, price, real_price, url, af_url, img_url, fetched_at, is_active)
SELECT 'B0D6YTCF7Z', 'Lenovo', 'Lenovo Tab K11 TB330XU タブレット - 11インチ WUXGA - MediaTek MT6769H Helio G88 (12 nm) オクタコア - 8GB - 128GB ストレージ - Android 13-4G - ルナグレー', NULL, 'android', '13', 'Helio G88', 11, NULL, 128, 11.0, '1920x1200', NULL, 10, NULL, NULL, false, 50519, 50519, 'https://www.amazon.co.jp/dp/B0D6YTCF7Z', 'https://www.amazon.co.jp/dp/B0D6YTCF7Z?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/51FVF9W+J4L._SL160_.jpg', '2026-06-21', true
WHERE NOT EXISTS (SELECT 1 FROM am_tablet_data WHERE asin = 'B0D6YTCF7Z' OR (url ILIKE '%B0D6YTCF7Z%' OR af_url ILIKE '%B0D6YTCF7Z%'));
INSERT INTO am_tablet_data (asin, brand, name, series, os_family, os_version, soc, soc_score, ram_gb, rom_gb, display_size_inch, resolution, refresh_rate_hz, battery_life_hours, battery_capacity_mah, weight_g, has_cellular, price, real_price, url, af_url, img_url, fetched_at, is_active)
SELECT 'B0CXDSJZZZ', 'Lenovo', 'Lenovo タブレット Tab B11 10.95インチ MediaTek Helio G88 Android13 重量465g LTE対応 Wi-Fi対応 ルナグレー ZADB0291JP', NULL, 'android', '13', 'Helio G88', 11, 4, 128, 10.95, '1920x1200', NULL, NULL, NULL, 465, true, 43800, 43800, 'https://www.amazon.co.jp/dp/B0CXDSJZZZ', 'https://www.amazon.co.jp/dp/B0CXDSJZZZ?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/41FdzdaLSLL._SL160_.jpg', '2026-06-21', true
WHERE NOT EXISTS (SELECT 1 FROM am_tablet_data WHERE asin = 'B0CXDSJZZZ' OR (url ILIKE '%B0CXDSJZZZ%' OR af_url ILIKE '%B0CXDSJZZZ%'));
INSERT INTO am_tablet_data (asin, brand, name, series, os_family, os_version, soc, soc_score, ram_gb, rom_gb, display_size_inch, resolution, refresh_rate_hz, battery_life_hours, battery_capacity_mah, weight_g, has_cellular, price, real_price, url, af_url, img_url, fetched_at, is_active)
SELECT 'B0DBKLCMY2', 'Lenovo', 'Lenovo Tab Plus タブレット (11.5インチ ワイド パネル MediaTek Helio G99 プロセッサー 8GB 256GB Wi-Fiモデル) グレー ZADX0061JP 【AndroidOS】', NULL, 'android', '14', 'Helio G99', 15, 8, 256, 11.5, '2000x1200', NULL, NULL, NULL, NULL, false, 41394, 41394, 'https://www.amazon.co.jp/dp/B0DBKLCMY2', 'https://www.amazon.co.jp/dp/B0DBKLCMY2?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/41vK4WvSnxL._SL160_.jpg', '2026-06-21', true
WHERE NOT EXISTS (SELECT 1 FROM am_tablet_data WHERE asin = 'B0DBKLCMY2' OR (url ILIKE '%B0DBKLCMY2%' OR af_url ILIKE '%B0DBKLCMY2%'));
INSERT INTO am_tablet_data (asin, brand, name, series, os_family, os_version, soc, soc_score, ram_gb, rom_gb, display_size_inch, resolution, refresh_rate_hz, battery_life_hours, battery_capacity_mah, weight_g, has_cellular, price, real_price, url, af_url, img_url, fetched_at, is_active)
SELECT 'B0FXBT9CYP', 'サムスン(SAMSUNG)', 'Samsung Galaxy Tab A11+ Plus 2026 (128GB 6GB Wi-Fiのみ) 11インチ 90Hz Android 16 タブレット オールデイバッテリー オクタコア (4nm) 4スピーカー 国際モデル X230 | 高速充電キューブバンドル | ', NULL, 'android', '16', 'Dimensity 7300', 22, 6, 128, 11.0, '1920x1200', 90, NULL, 7040, NULL, false, 53361, 53361, 'https://www.amazon.co.jp/dp/B0FXBT9CYP', 'https://www.amazon.co.jp/dp/B0FXBT9CYP?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/31I3rlFAoHL._SL160_.jpg', '2026-06-21', true
WHERE NOT EXISTS (SELECT 1 FROM am_tablet_data WHERE asin = 'B0FXBT9CYP' OR (url ILIKE '%B0FXBT9CYP%' OR af_url ILIKE '%B0FXBT9CYP%'));
INSERT INTO am_tablet_data (asin, brand, name, series, os_family, os_version, soc, soc_score, ram_gb, rom_gb, display_size_inch, resolution, refresh_rate_hz, battery_life_hours, battery_capacity_mah, weight_g, has_cellular, price, real_price, url, af_url, img_url, fetched_at, is_active)
SELECT 'B0F9P4719Q', 'xiaomi(シャオミ)', 'シャオミ(Xiaomi) タブレット Redmi Pad 2 4GB+128GB グラファイトグレー wi-fiモデル 2.5K 大型11インチディスプレ Dolby Atmos対応 9000mAh 大容量 バッテリー 高性能チップHelio G100-Ultra 2TBまでmi', NULL, 'android', NULL, 'Helio G100', 16, 4, 128, 11.0, NULL, NULL, NULL, 9000, NULL, false, 27980, 27980, 'https://www.amazon.co.jp/dp/B0F9P4719Q', 'https://www.amazon.co.jp/dp/B0F9P4719Q?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/31993xtqsJL._SL160_.jpg', '2026-06-21', true
WHERE NOT EXISTS (SELECT 1 FROM am_tablet_data WHERE asin = 'B0F9P4719Q' OR (url ILIKE '%B0F9P4719Q%' OR af_url ILIKE '%B0F9P4719Q%'));
INSERT INTO am_tablet_data (asin, brand, name, series, os_family, os_version, soc, soc_score, ram_gb, rom_gb, display_size_inch, resolution, refresh_rate_hz, battery_life_hours, battery_capacity_mah, weight_g, has_cellular, price, real_price, url, af_url, img_url, fetched_at, is_active)
SELECT 'B0CJF6SCVL', 'xiaomi(シャオミ)', 'Xiaomi Redmi Pad SE タブレット 6GB + 128GB Wi-fi版 日本語対応 11インチ FHD+ アイケア ディスプレイ 90Hz高精細 8000mAh 大容量バッテリー 軽量ボディ Snapdragon 680 MIUI 14 Android 13 D', NULL, 'android', '13', 'Snapdragon 680', 12, 4, 128, 11.0, NULL, 90, 19, 8000, 478, false, 37800, 37800, 'https://www.amazon.co.jp/dp/B0CJF6SCVL', 'https://www.amazon.co.jp/dp/B0CJF6SCVL?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/313MDUNkR1L._SL160_.jpg', '2026-06-21', true
WHERE NOT EXISTS (SELECT 1 FROM am_tablet_data WHERE asin = 'B0CJF6SCVL' OR (url ILIKE '%B0CJF6SCVL%' OR af_url ILIKE '%B0CJF6SCVL%'));
INSERT INTO am_tablet_data (asin, brand, name, series, os_family, os_version, soc, soc_score, ram_gb, rom_gb, display_size_inch, resolution, refresh_rate_hz, battery_life_hours, battery_capacity_mah, weight_g, has_cellular, price, real_price, url, af_url, img_url, fetched_at, is_active)
SELECT 'B0GKFHK6XN', 'ALLDOCUBE', 'ALLDOCUBE iPlay70 Pad Pro タブレット12インチ Android16 2560x1600解像度 90Hz 10000mAh PD33W Helio G100 16GB+128GB 4スピーカー WidevineL1 PCモード 顔認証 GPS 電子コンパス', NULL, 'android', '16', 'Helio G100', 16, 16, 128, 12.0, '2560x1600', 90, NULL, 10000, NULL, true, 29999, 29999, 'https://www.amazon.co.jp/dp/B0GKFHK6XN', 'https://www.amazon.co.jp/dp/B0GKFHK6XN?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/41RSWzz01dL._SL160_.jpg', '2026-06-21', true
WHERE NOT EXISTS (SELECT 1 FROM am_tablet_data WHERE asin = 'B0GKFHK6XN' OR (url ILIKE '%B0GKFHK6XN%' OR af_url ILIKE '%B0GKFHK6XN%'));

COMMIT;
