-- Specsy mini-pc product INSERT SQL generated on 2026-06-19
-- Review candidates before running this in Supabase SQL Editor.
BEGIN;

ALTER TABLE am_pc_data ADD COLUMN IF NOT EXISTS condition_label text;
ALTER TABLE am_pc_data ADD COLUMN IF NOT EXISTS availability text;
ALTER TABLE am_pc_data ADD COLUMN IF NOT EXISTS is_used boolean DEFAULT false;
ALTER TABLE am_pc_data ADD COLUMN IF NOT EXISTS is_refurbished boolean DEFAULT false;
ALTER TABLE am_pc_data ADD COLUMN IF NOT EXISTS gpu text;
ALTER TABLE am_pc_data ADD COLUMN IF NOT EXISTS gpu_class text;
ALTER TABLE am_pc_data ADD COLUMN IF NOT EXISTS gpu_score integer;
ALTER TABLE am_pc_data ADD COLUMN IF NOT EXISTS has_dgpu boolean DEFAULT false;

INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'MiniPC', NULL, 'sincoole', 'Sincoole N100 Mini PC、12th N100 Windows 11 Pro (最大3.4GHz) ミニコンピューター、8GB RAM 128GB SSD、USB3.2、Mini PC', '新品', 'IN_STOCK', false, false, 41841, 41841, 'N100', 'Intel UHD Graphics', 'integrated', 2, false, 8, 128, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0DS2LZMXX', 'https://www.amazon.co.jp/dp/B0DS2LZMXX?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/31eh--bAcRL._SL160_.jpg', '', '2026-06-19', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0DS2LZMXX%' OR af_url ILIKE '%B0DS2LZMXX%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'MiniPC', NULL, 'GMKtec', 'GMKtec ミニPC G3S 第12世代 Intel N95 Windows11 Pro 搭載 ミニPC｜4コア4スレッド｜最大3.4GHz｜小型PC・超軽量｜WIFI5/BT5.0｜2画面出力・V Core i3-10110U', '新品', 'IN_STOCK', false, false, 41099, 41099, 'Core i3-10110U', 'Intel UHD Graphics', 'integrated', 2, false, 8, 512, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0GGBF6YMK', 'https://www.amazon.co.jp/dp/B0GGBF6YMK?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/41F0wMCDYkL._SL160_.jpg', '', '2026-06-19', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0GGBF6YMK%' OR af_url ILIKE '%B0GGBF6YMK%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'MiniPC', NULL, 'GMKtec', 'GMKtec ミニpc G3 Pro 初登場 Win11 Pro mini pc 最大4.1GHz WIFI6 BT5.2 小型 M.2 2242 ミニパソコン 2画面出力 超軽量 高性能 みにpc Core i3-10110U', '新品', 'IN_STOCK', false, false, 53238, 53238, 'Core i3-10110U', 'Integrated', 'integrated', 2, false, 64, 8192, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0GS1MK74D', 'https://www.amazon.co.jp/dp/B0GS1MK74D?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/41F0wMCDYkL._SL160_.jpg', '', '2026-06-19', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0GS1MK74D%' OR af_url ILIKE '%B0GS1MK74D%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'MiniPC', NULL, 'Getorli', 'Getorli ミニPC AMD Ryzen 5300U搭載 -16GB RAM 512GB SSD デュアル2.5G LAN＆WiFi6対応 小型パソコン、3画面出力可能 コンパクトpc オフィス/ N150', '新品', 'IN_STOCK_SCARCE', false, false, 46998, 46998, 'N150', 'Integrated', 'integrated', 2, false, 64, 512, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0GHRGTXNH', 'https://www.amazon.co.jp/dp/B0GHRGTXNH?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/312Suqx9ToL._SL160_.jpg', '', '2026-06-19', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0GHRGTXNH%' OR af_url ILIKE '%B0GHRGTXNH%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'MiniPC', NULL, 'GEEKOM', 'GEEKOM 「初心者·法人にも」GEEKOM ミニpcIntel N95搭載 最大16GB+2TB拡張可能｜6USB·4Kデュアル出力·VESA対応｜静音·省電力｜正規Win11 Pro搭載ミニPC｜在宅/オフィ Core i3-10110U', '新品', 'IN_STOCK', false, false, 39998, 39998, 'Core i3-10110U', 'Integrated', 'integrated', 2, false, 16, 2048, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0GS9DDK59', 'https://www.amazon.co.jp/dp/B0GS9DDK59?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/418u9f0b27L._SL160_.jpg', '', '2026-06-19', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0GS9DDK59%' OR af_url ILIKE '%B0GS9DDK59%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'MiniPC', NULL, 'Beelink', 'Beelink MINI-S12 Pro Win11ミニPC、Alder Lake-N100 プロセッサー 最大3.40GHz、12GB LPDDR5 RAM 512GB SSD 搭載、 2画面同時出', '新品', 'IN_STOCK', false, false, 56900, 56900, 'N100', 'Integrated', 'integrated', 2, false, 12, 512, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0C8CL18H3', 'https://www.amazon.co.jp/dp/B0C8CL18H3?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/41SrRZXkoiL._SL160_.jpg', '', '2026-06-19', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0C8CL18H3%' OR af_url ILIKE '%B0C8CL18H3%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'MiniPC', NULL, 'skynew', 'Skynew ミニpc インテル N150 12GB LPDDR5 小型 軽量 省電力 512GB Nvme SSD / Windows11Home デスクトップpc 持ち運び Wi-Fi6 品番 M', '新品', 'IN_STOCK_SCARCE', false, false, 77000, 77000, 'N150', 'Integrated', 'integrated', 2, false, 12, 512, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0GP5LB6GD', 'https://www.amazon.co.jp/dp/B0GP5LB6GD?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/41P4yvHGAWL._SL160_.jpg', '', '2026-06-19', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0GP5LB6GD%' OR af_url ILIKE '%B0GP5LB6GD%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'MiniPC', NULL, 'Beelink', 'Beelink 第12世代Intel Alder Lake-N95プロセッサー（最大3.40GHz） Wi-11 ミニコンピューター、MINI-S12、12GB RAM 256GB SSD ビジネスミ', '新品', 'IN_STOCK_SCARCE', false, false, 47900, 47900, 'N95', 'Intel UHD Graphics', 'integrated', 2, false, 12, 256, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0BWM1JWSY', 'https://www.amazon.co.jp/dp/B0BWM1JWSY?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/41SrRZXkoiL._SL160_.jpg', '', '2026-06-19', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0BWM1JWSY%' OR af_url ILIKE '%B0BWM1JWSY%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'MiniPC', NULL, 'NiPoGi', 'NiPoGi AMD Ryzen 4300U mini pc 最大3.7GHz 4C/4T Win11 Pro 16GB+M.2 2280 256GB（4TB換装可）みにPC フル機能Type-C/DP1.4/HD N95', '新品', 'IN_STOCK_SCARCE', false, false, 40998, 40998, 'N95', 'Integrated', 'integrated', 2, false, 64, 4096, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0FNCYLXLM', 'https://www.amazon.co.jp/dp/B0FNCYLXLM?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/41CgtnBJ1rL._SL160_.jpg', '', '2026-06-19', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0FNCYLXLM%' OR af_url ILIKE '%B0FNCYLXLM%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'MiniPC', NULL, 'Beelink', 'Beelink EQ14 ミニPC、Intel Twin Lake N150 ミニゲーミング PC、16GB DDR4 1TB SSD ミニコンピューター (4C/4T、最大 3.6 GHz) WiF', '新品', 'IN_STOCK', false, false, 57900, 57900, 'N150', 'Integrated', 'integrated', 2, false, 16, 1024, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0DR8RS2PZ', 'https://www.amazon.co.jp/dp/B0DR8RS2PZ?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/61BZOrRkMBL._SL160_.jpg', '', '2026-06-19', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0DR8RS2PZ%' OR af_url ILIKE '%B0DR8RS2PZ%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'MiniPC', NULL, 'ＴＩＴＡＮ　ＡＲＭＹ', 'ＴＩＴＡＮ　ＡＲＭＹ リンクスインターナショナル LNDS150 ミニPC Intel N150 メモリ16GB ストレージ256GB Window 10 IoT ファンレス小型デスクトップパソコン LNDS150-16/', '新品', 'IN_STOCK_SCARCE', false, false, 63100, 63100, 'N150', 'Integrated', 'integrated', 2, false, 16, 256, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0GX32FT36', 'https://www.amazon.co.jp/dp/B0GX32FT36?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/31UQULw2oiL._SL160_.jpg', '', '2026-06-19', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0GX32FT36%' OR af_url ILIKE '%B0GX32FT36%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'MiniPC', NULL, 'WayPonDEV', 'WayPonDEV youyeetoo BY53 ミニPC Windows 11搭載  12GB DDR5 512GB SSD 4K出力 超小型デスクトップパソコン オフィス 在宅ワーク ホームエンタメに最適(12GB+ N150', '新品', 'LEADTIME', false, false, 37880, 37880, 'N150', 'Integrated', 'integrated', 2, false, 12, 512, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0FWR17RYK', 'https://www.amazon.co.jp/dp/B0FWR17RYK?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/31d-ctnhWeL._SL160_.jpg', '', '2026-06-19', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0FWR17RYK%' OR af_url ILIKE '%B0FWR17RYK%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'MiniPC', NULL, 'ACEMAGIC', 'ACEMAGIC ミニpc ryzen 4300U mini pc Type-C/HDMI/DP 4K×3画面 4C/4T 最大3.7GHz ミニパソコン Windows11 Pro USB3.2×6 N100', '新品', 'IN_STOCK_SCARCE', false, false, 45998, 45998, 'N100', 'Integrated', 'integrated', 2, false, 16, 1024, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0F5459XJD', 'https://www.amazon.co.jp/dp/B0F5459XJD?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/31hEvCZPntL._SL160_.jpg', '', '2026-06-19', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0F5459XJD%' OR af_url ILIKE '%B0F5459XJD%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'MiniPC', NULL, 'GMKtec', 'GMKtecミニpc 最新第12世代インテルTwin Lake-N150 mini pc Windows 11 Pro DDR5 12GB+512G SSD 4コア/4スレッド 7nm 最大周波数3.', '新品', 'LEADTIME', false, false, 119596, 119596, 'N150', 'Intel UHD Graphics', 'integrated', 2, false, 12, 512, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0CCDL6VS3', 'https://www.amazon.co.jp/dp/B0CCDL6VS3?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/41i4JcOAh6L._SL160_.jpg', '', '2026-06-19', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0CCDL6VS3%' OR af_url ILIKE '%B0CCDL6VS3%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'MiniPC', NULL, 'ノーブランド品', 'ノーブランド品 ミニpc n150 mini pc 8GB RAM 256GB SSD 最大3.6GHz 4C4T Windows 11 静音 高速放熱 青 N150', '新品', 'IN_STOCK_SCARCE', false, false, 39998, 39998, 'N150', 'Integrated', 'integrated', 2, false, 8, 256, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0FBV7HF1G', 'https://www.amazon.co.jp/dp/B0FBV7HF1G?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/31QAGbK8K8L._SL160_.jpg', '', '2026-06-19', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0FBV7HF1G%' OR af_url ILIKE '%B0FBV7HF1G%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'MiniPC', NULL, 'GMKtec', 'GMKtec ミニ PC Ryzen 5 3500U搭載 N150/N97 より速い GMKtec G10 mini pc最大3.7GHz Win11 pro ミニPC 2.5G 有線LANポート4K3画面出力可能', '新品', 'IN_STOCK_SCARCE', false, false, 42999, 42999, 'Ryzen 5 3500U', 'Integrated', 'integrated', 2, false, 64, 256, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0GJSR4LRB', 'https://www.amazon.co.jp/dp/B0GJSR4LRB?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/3192FAJOGEL._SL160_.jpg', '', '2026-06-19', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0GJSR4LRB%' OR af_url ILIKE '%B0GJSR4LRB%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'MiniPC', NULL, 'Getorli', 'Getorli ミニpc Ryzen 5 3550H搭載 mini pc - 最大3.7GHz 4コア8スレッド WiFi6/Bluetooth5.3対応 3画面出力対応 デュアルHDMI Type-', '新品', 'IN_STOCK_SCARCE', false, false, 39998, 39998, 'Ryzen 5 3550H', 'Integrated', 'integrated', 2, false, 16, 512, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0GQLSMZZ1', 'https://www.amazon.co.jp/dp/B0GQLSMZZ1?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/31O9gKXkLLL._SL160_.jpg', '', '2026-06-19', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0GQLSMZZ1%' OR af_url ILIKE '%B0GQLSMZZ1%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'MiniPC', NULL, 'GMKtec', 'GMKtec ミニPC Ryzen 7 7730U搭載 M5 Ultra8コア16スレッド 最大4.5GHz Win11 Pro 小型PC 2.5G有線LAN Wi-Fi 6E Bluetooth 5', '新品', 'IN_STOCK_SCARCE', false, false, 79990, 79990, 'Ryzen 7 7730U', 'Integrated', 'integrated', 2, false, 32, 1024, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0GXZW56L3', 'https://www.amazon.co.jp/dp/B0GXZW56L3?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/41NxD91OSXL._SL160_.jpg', '', '2026-06-19', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0GXZW56L3%' OR af_url ILIKE '%B0GXZW56L3%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'MiniPC', NULL, 'NiPoGi', 'NiPoGi ミニpc Ryzen 7 7730U 8C/16T 最大4.5GHz mini pc ryzen 16GB DDR4 512GB SSD 4K60Hz ミニパソコン 3画面出力 小型pc', '新品', 'IN_STOCK', false, false, 67448, 67448, 'Ryzen 7 7730U', 'Integrated', 'integrated', 2, false, 16, 512, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0G52HH15X', 'https://www.amazon.co.jp/dp/B0G52HH15X?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/413dUluRg3L._SL160_.jpg', '', '2026-06-19', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0G52HH15X%' OR af_url ILIKE '%B0G52HH15X%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'MiniPC', NULL, 'GMKtec', 'GMKtec ミニPC AMD Ryzen7 8845HS搭載 128GB DDR5＋8TB SSD拡張可｜Oculink＋USB4.0×2搭載 MAX 5.1GHz｜Win 11 Pro デュアル2 Ryzen 7 8845HS', '新品', 'IN_STOCK', false, false, 56998, 56998, 'Ryzen 7 8845HS', 'GTX 1650', 'dgpu', 3, true, 28, 8192, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0G3PLYN89', 'https://www.amazon.co.jp/dp/B0G3PLYN89?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/41d3oy9kCGL._SL160_.jpg', '', '2026-06-19', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0G3PLYN89%' OR af_url ILIKE '%B0G3PLYN89%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'MiniPC', NULL, 'GMKtec', 'GMKtec ゲーミングミニPC AMD Ryzen 7 7730U (8C/16T Max4.5GHz) mini pc 16GB SSD 512GB Windows 11 Pro 3画面同時出力', '新品', 'IN_STOCK', false, false, 79998, 79998, 'Ryzen 7 7730U', 'Integrated', 'integrated', 2, false, 16, 512, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0FRB19ZZ1', 'https://www.amazon.co.jp/dp/B0FRB19ZZ1?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/41BIBJFC99L._SL160_.jpg', '', '2026-06-19', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0FRB19ZZ1%' OR af_url ILIKE '%B0FRB19ZZ1%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'MiniPC', NULL, 'CHUWI', 'CHUWIミニPC AuBox AMD Ryzen 7 8745HS (8C/16T)最大4.9GHz mini pc DDR5 16GB 512GB SSD Windows 11 Pro Offic', '新品', 'IN_STOCK', false, false, 81900, 81900, 'Ryzen 7 8745HS', 'Radeon 780M', 'integrated', 4, false, 64, 512, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0FD3G3CV9', 'https://www.amazon.co.jp/dp/B0FD3G3CV9?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/31Bi5mo6nwL._SL160_.jpg', '', '2026-06-19', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0FD3G3CV9%' OR af_url ILIKE '%B0FD3G3CV9%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'MiniPC', NULL, 'YCTipc', 'YCTipc ZHR ミニ PC AMD Ryzen 7 7735HS 8C/16T 4.75GHz｜16GB DDR5 512GB SSD 高性能ミニパソコン｜デュアル 2.5G有線LAN搭載WiF', '新品', 'IN_STOCK_SCARCE', false, false, 62998, 62998, 'Ryzen 7 7735HS', 'Integrated', 'integrated', 2, false, 16, 512, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0FG7YKBSC', 'https://www.amazon.co.jp/dp/B0FG7YKBSC?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/31-5w7v3LWL._SL160_.jpg', '', '2026-06-19', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0FG7YKBSC%' OR af_url ILIKE '%B0FG7YKBSC%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'MiniPC', NULL, 'GMKtec', 'GMKtec M5 Ultra ゲーミングミニPC AMD Ryzen 7 7730U（7430U／5825U アップグレード版） 16GB RAM 512GB SSD デュアル2.5GbE LAN', '新品', 'IN_STOCK_SCARCE', false, false, 78749, 78749, 'Ryzen 7 7730U', 'Integrated', 'integrated', 2, false, 16, 512, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0GGDYVQQS', 'https://www.amazon.co.jp/dp/B0GGDYVQQS?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/41uampKaXNL._SL160_.jpg', '', '2026-06-19', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0GGDYVQQS%' OR af_url ILIKE '%B0GGDYVQQS%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'MiniPC', NULL, 'Fsjun', 'Fsjun ミニpc win11&2024 office AMD Ryzen 7 5825U (8C/16T 周波数4.40GHz) DDR4 16GB/Pcie NVME 512GB SSD Min', '新品', 'IN_STOCK', false, false, 65999, 65999, 'Ryzen 7 5825U', 'Integrated', 'integrated', 2, false, 16, 512, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0GWC8P4L1', 'https://www.amazon.co.jp/dp/B0GWC8P4L1?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/51gMPVTLTbL._SL160_.jpg', '', '2026-06-19', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0GWC8P4L1%' OR af_url ILIKE '%B0GWC8P4L1%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'MiniPC', NULL, 'Getorli', 'Getorli ミニPC AMD Ryzen 7 8745HS 搭載 8コア/16スレッド 高性能mini PC 4画面出力 16GB DDR5 1TB SSD デュアル2.5G LAN 業務用/クリ', '新品', 'IN_STOCK', false, false, 79998, 79998, 'Ryzen 7 8745HS', 'Integrated', 'integrated', 2, false, 16, 1024, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0GQBG3573', 'https://www.amazon.co.jp/dp/B0GQBG3573?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/31F0nCsQZBL._SL160_.jpg', '', '2026-06-19', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0GQBG3573%' OR af_url ILIKE '%B0GQBG3573%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'MiniPC', NULL, 'Getorli', 'Getorli ミニPC AMD Ryzen 7 6800H 搭載 32GB LPDDR5 1TB SSD Radeon 680M 小型デスクトップ 最大3画面4K出力 HDMI/DP/Type-C', '新品', 'IN_STOCK', false, false, 79998, 79998, 'Ryzen 7 6800H', 'Integrated', 'integrated', 2, false, 32, 1024, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0GQGX47K1', 'https://www.amazon.co.jp/dp/B0GQGX47K1?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/319kRyzo8HL._SL160_.jpg', '', '2026-06-19', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0GQGX47K1%' OR af_url ILIKE '%B0GQGX47K1%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'MiniPC', NULL, 'Getorli', 'Getorli ミニPC AMD Ryzen™ 7 PRO 8845HS 搭載 32GB DDR5 1TB SSD 高速 小型PC Radeon 780M 4画面出力 Wi-Fi6 業務用/クリエイテ Ryzen 7', '新品', 'IN_STOCK_SCARCE', false, false, 96998, 96998, 'Ryzen 7', 'Radeon 780M', 'integrated', 4, false, 32, 1024, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0H23V52NQ', 'https://www.amazon.co.jp/dp/B0H23V52NQ?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/41Q0fmqrcDL._SL160_.jpg', '', '2026-06-19', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0H23V52NQ%' OR af_url ILIKE '%B0H23V52NQ%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'MiniPC', NULL, 'ACEMAGIC', 'ACEMAGIC ミニPC Ryzen 7 7730U 8C/16T 最大4.5GHz mini pc Windows11 Pro Type-C/HDMI2.0/DP1.4 4K 3画面 ミニパソコン', '新品', 'IN_STOCK_SCARCE', false, false, 66100, 66100, 'Ryzen 7 7730U', 'Integrated', 'integrated', 2, false, 64, 512, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0DRNX5971', 'https://www.amazon.co.jp/dp/B0DRNX5971?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/316pjKyhBqL._SL160_.jpg', '', '2026-06-19', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0DRNX5971%' OR af_url ILIKE '%B0DRNX5971%'));

COMMIT;
