-- Specsy desktop-pc product INSERT SQL generated on 2026-06-20
-- Review candidates before running this in Supabase SQL Editor.
BEGIN;

ALTER TABLE am_pc_data ADD COLUMN IF NOT EXISTS condition_label text;
ALTER TABLE am_pc_data ADD COLUMN IF NOT EXISTS availability text;
ALTER TABLE am_pc_data ADD COLUMN IF NOT EXISTS is_used boolean DEFAULT false;
ALTER TABLE am_pc_data ADD COLUMN IF NOT EXISTS is_refurbished boolean DEFAULT false;
ALTER TABLE am_pc_data ADD COLUMN IF NOT EXISTS gpu text;
ALTER TABLE am_pc_data ADD COLUMN IF NOT EXISTS gpu_class text;
ALTER TABLE am_pc_data ADD COLUMN IF NOT EXISTS gpu_score integer;
ALTER TABLE am_pc_data ADD COLUMN IF NOT EXISTS has_dgpu boolean DEFAULT false;

INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'TITAN GAMING', 'TITAN GAMING ゲーミングPC デスクトップパソコン GeForce RTX 5060 Ti 8GB Ryzen 7 5700X メモリ16GB NVMe SSD 512GB Windows', '新品', 'LEADTIME', false, false, 183000, 183000, 'Ryzen 7 5700X', 'RTX 5060', 'dgpu', 8, true, 16, 512, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0GRJGH6LH', 'https://www.amazon.co.jp/dp/B0GRJGH6LH?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/41XEMz+923L._SL160_.jpg', '', '2026-06-20', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0GRJGH6LH%' OR af_url ILIKE '%B0GRJGH6LH%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'DARUMA', 'DARUMA-PC デスクトップPC (Ryzen5 5500GT / 16GB メモリ/ 500GB SSD/DVI+ HDMI+ VGA/Windows 11 HOME Wi-Fi Ryzen 5 5500GT', '新品', 'IN_STOCK_SCARCE', false, false, 79800, 79800, 'Ryzen 5 5500GT', 'Integrated', 'integrated', 2, false, 16, 500, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0GH7F9QXB', 'https://www.amazon.co.jp/dp/B0GH7F9QXB?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/31ca1VWRXML._SL160_.jpg', '', '2026-06-20', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0GH7F9QXB%' OR af_url ILIKE '%B0GH7F9QXB%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'ＮＥＷＬＥＡＧＵＥ', 'ＮＥＷＬＥＡＧＵＥ NEWLEAGUE デスクトップPC, Core i5 14400搭載, 16GBメモリ, 512GB SSD, Windows11 Pro, WPS Office, WIFI子機無償プレゼント, ス Core i5-14400', '新品', 'IN_STOCK_SCARCE', false, false, 99800, 99800, 'Core i5-14400', 'Integrated', 'integrated', 2, false, 16, 512, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0F28KWT5P', 'https://www.amazon.co.jp/dp/B0F28KWT5P?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/31w7wcxzFKL._SL160_.jpg', '', '2026-06-20', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0F28KWT5P%' OR af_url ILIKE '%B0F28KWT5P%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'ＮＥＷＬＥＡＧＵＥ', 'ＮＥＷＬＥＡＧＵＥ NEWLEAGUE デスクトップPC, Core i5 14400搭載, 32GBメモリ, 1TB SSD, Win11 pro, WPS Office, WIFI子機無償プレゼント, スリムタワー型 Core i5-14400', '新品', 'IN_STOCK_SCARCE', false, false, 129800, 129800, 'Core i5-14400', 'Integrated', 'integrated', 2, false, 32, 1024, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0F28LRMPW', 'https://www.amazon.co.jp/dp/B0F28LRMPW?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/31w7wcxzFKL._SL160_.jpg', '', '2026-06-20', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0F28LRMPW%' OR af_url ILIKE '%B0F28LRMPW%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'DARUMA', 'DARUMA-PC デスクトップPC Core i5 14400 / 16GB メモリ/ 500GB SSD/HDMI/Windows 11 Pro/MS 2021 Wi-Fi 6 Core i5-14400', '新品', 'IN_STOCK', false, false, 99800, 99800, 'Core i5-14400', 'Integrated', 'integrated', 2, false, 16, 500, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0GM62V8K8', 'https://www.amazon.co.jp/dp/B0GM62V8K8?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/31fPyZdJLHL._SL160_.jpg', '', '2026-06-20', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0GM62V8K8%' OR af_url ILIKE '%B0GM62V8K8%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'ＮＥＷＬＥＡＧＵＥ', 'ＮＥＷＬＥＡＧＵＥ NEWLEAGUE デスクトップPC, Core i5 14400搭載, 32GBメモリ, 2TB SSD, Win11 pro, WPS Office, WIFI子機無償プレゼント, スリムタワー型 Core i5-14400', '新品', 'IN_STOCK_SCARCE', false, false, 149800, 149800, 'Core i5-14400', 'Integrated', 'integrated', 2, false, 32, 2048, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0F28LNNF5', 'https://www.amazon.co.jp/dp/B0F28LNNF5?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/31w7wcxzFKL._SL160_.jpg', '', '2026-06-20', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0F28LNNF5%' OR af_url ILIKE '%B0F28LNNF5%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'Dell', 'Dell デスクトップパソコン Dell Slim ECS1250 Core i5 14400 メモリ8GB SSD 512GB Windows 11 Home ブラック (2025春モデル) Core i5-14400', '新品', 'IN_STOCK_SCARCE', false, false, 144269, 144269, 'Core i5-14400', 'Integrated', 'integrated', 2, false, 8, 512, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0F4PYB64C', 'https://www.amazon.co.jp/dp/B0F4PYB64C?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/41hdCa9MN7L._SL160_.jpg', '', '2026-06-20', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0F4PYB64C%' OR af_url ILIKE '%B0F4PYB64C%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'DARUMA', 'DARUMA-PC デスクトップPCCore i5 14400 / メモリ32GB / SSD 1TB M2 NVMe Gen 4/ Windows 11 Pro & Office 2021 / DV Core i5-14400', '新品', 'IN_STOCK', false, false, 129800, 129800, 'Core i5-14400', 'RTX 4060', 'dgpu', 7, true, 32, 1024, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0D5MFBVSY', 'https://www.amazon.co.jp/dp/B0D5MFBVSY?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/41JKgQrX-kL._SL160_.jpg', '', '2026-06-20', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0D5MFBVSY%' OR af_url ILIKE '%B0D5MFBVSY%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'DARUMA', 'DARUMA-PC デスクトップPC Core i5 14400 / 16GB メモリ/ 500GB SSD/HDMI/Windows 11 HOME Wi-Fi 6 Bluetooth Core i5-14400', '新品', 'IN_STOCK_SCARCE', false, false, 92800, 92800, 'Core i5-14400', 'Integrated', 'integrated', 2, false, 16, 500, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0GM677W3F', 'https://www.amazon.co.jp/dp/B0GM677W3F?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/31fPyZdJLHL._SL160_.jpg', '', '2026-06-20', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0GM677W3F%' OR af_url ILIKE '%B0GM677W3F%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'ＮＥＷＬＥＡＧＵＥ', 'ＮＥＷＬＥＡＧＵＥ ゲーミングパソコン Ryzen 5 5600G / メモリ16GB / NVMe SSD 512GB / Windows11Pro / WPS Office ミドルタワー デスクトップパソコン (Ry', '新品', 'IN_STOCK_SCARCE', false, false, 95800, 95800, 'Ryzen 5 5600G', 'Integrated', 'integrated', 2, false, 16, 512, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B09RPTMPZ3', 'https://www.amazon.co.jp/dp/B09RPTMPZ3?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/41t+tXZmx0L._SL160_.jpg', '', '2026-06-20', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B09RPTMPZ3%' OR af_url ILIKE '%B09RPTMPZ3%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'DARUMA', 'DARUMA-PC デスクトップPC Ryzen 5 / 16GB メモリ/ M2 NVMe SSD 256GB / DVI+ HDMI+ VGA/Windows 11 HOME Wi-Fi ，Rad Ryzen 5 3400G', '新品', 'IN_STOCK_SCARCE', false, false, 59800, 59800, 'Ryzen 5 3400G', 'Integrated', 'integrated', 2, false, 16, 256, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0GM67P8SQ', 'https://www.amazon.co.jp/dp/B0GM67P8SQ?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/31fPyZdJLHL._SL160_.jpg', '', '2026-06-20', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0GM67P8SQ%' OR af_url ILIKE '%B0GM67P8SQ%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'Generic', 'Generic PC-TECH デスクトップパソコン Ryzen 5 3400G / メモリー16GB / 高速&大容量 M.2 NvMe SSD 1TB / Radeon™ RX Vega 11 Graphics', '新品', 'LEADTIME', false, false, 89980, 89980, 'Ryzen 5 3400G', 'Integrated', 'integrated', 2, false, 16, 1024, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0GTZ8S27N', 'https://www.amazon.co.jp/dp/B0GTZ8S27N?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/31rNy++VkEL._SL160_.jpg', '', '2026-06-20', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0GTZ8S27N%' OR af_url ILIKE '%B0GTZ8S27N%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'HP', 'HP デスクトップPC タワー型 OmniDesk AMD Ryzen 5 8500G プロセッサー 16GBメモリ 1TB SSD Windows11 Home (型番：B87KYPA-AAAA)', '新品', 'LEADTIME', false, false, 149800, 149800, 'Ryzen 5 8500G', 'Integrated', 'integrated', 2, false, 16, 1024, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0DZ5X9H8G', 'https://www.amazon.co.jp/dp/B0DZ5X9H8G?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/31WavdKe9cL._SL160_.jpg', '', '2026-06-20', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0DZ5X9H8G%' OR af_url ILIKE '%B0DZ5X9H8G%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'DARUMA', 'DARUMA-PC デスクトップPC Ryzen 5, 16GB メモリ/ M2 NVMe SSD 256GB / DVI+ HDMI+ VGA/Windows 11 Pro/MS 2021 Wi-F Ryzen 5 3400G', '新品', 'IN_STOCK_SCARCE', false, false, 78800, 78800, 'Ryzen 5 3400G', 'Integrated', 'integrated', 2, false, 16, 256, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0GM62L57Q', 'https://www.amazon.co.jp/dp/B0GM62L57Q?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/31fPyZdJLHL._SL160_.jpg', '', '2026-06-20', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0GM62L57Q%' OR af_url ILIKE '%B0GM62L57Q%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'Generic', 'Generic PC-TECH ゲーミングデスクトップパソコン Ryzen 5 5500 / RTX 5060Ti / メモリー32GB / 高速&大容量 M.2 NvMe SSD 1TB / B550M / Win', '新品', 'LEADTIME', false, false, 205000, 205000, 'Ryzen 5 5500', 'RTX 5060', 'dgpu', 8, true, 32, 1024, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0GVS1Y79B', 'https://www.amazon.co.jp/dp/B0GVS1Y79B?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/31rNy++VkEL._SL160_.jpg', '', '2026-06-20', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0GVS1Y79B%' OR af_url ILIKE '%B0GVS1Y79B%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'Geame', 'Geame（ジーム） ゲーミングPC デスクトップ タワー型 ゲームピーシー Geforce RTX 3050 Ryzen 5 4500 cpu 16GB メモリ 500GB SSD WiFi Win', '新品', 'IN_STOCK_SCARCE', false, false, 134800, 134800, 'Ryzen 5 4500', 'Integrated', 'integrated', 2, false, 16, 500, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0FNWQDLGG', 'https://www.amazon.co.jp/dp/B0FNWQDLGG?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/51d9m8A-2OL._SL160_.jpg', '', '2026-06-20', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0FNWQDLGG%' OR af_url ILIKE '%B0FNWQDLGG%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'KENDOVIVI', 'KENDOVIVI 仕事向けデスクトップパソコン Ryzen 5 5600g メモリ16GB SSD500GB AMD CPU搭載 Windows 11 Pro Ryzen 5 5600G', '新品', 'LEADTIME', false, false, 89800, 89800, 'Ryzen 5 5600G', 'Integrated', 'integrated', 2, false, 16, 500, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0CGZCJPWP', 'https://www.amazon.co.jp/dp/B0CGZCJPWP?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/31ST2y+kTJL._SL160_.jpg', '', '2026-06-20', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0CGZCJPWP%' OR af_url ILIKE '%B0CGZCJPWP%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'TITAN GAMING', 'TITAN GAMING ゲーミングPC デスクトップパソコン GeForce RTX 5060 Ryzen 7 5700X メモリ16GB NVMe SSD 512GB Windows 11 Hom', '新品', 'LEADTIME', false, false, 172000, 172000, 'Ryzen 7 5700X', 'RTX 5060', 'dgpu', 8, true, 16, 512, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0GRJHKKFQ', 'https://www.amazon.co.jp/dp/B0GRJHKKFQ?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/41XEMz+923L._SL160_.jpg', '', '2026-06-20', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0GRJHKKFQ%' OR af_url ILIKE '%B0GRJHKKFQ%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'DARUMA', 'DARUMA ゲーミングPCRyzen5 5500 / メモリ16GB / SSD 1TB M2 NVMe / B550M Pro4 / Windows 11 Home / 拡張可能650W 80PLUS電源 /ゲ Ryzen 5 5500', '新品', 'IN_STOCK_SCARCE', false, false, 122800, 122800, 'Ryzen 5 5500', 'Integrated', 'integrated', 2, false, 16, 1024, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0GH7L59QZ', 'https://www.amazon.co.jp/dp/B0GH7L59QZ?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/51+iHKZjXbL._SL160_.jpg', '', '2026-06-20', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0GH7L59QZ%' OR af_url ILIKE '%B0GH7L59QZ%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'TITAN GAMING', 'TITAN GAMING ゲーミングPC デスクトップパソコン GeForce RTX 3050 Ryzen 5 5500 メモリ16GB NVMe SSD 512GB Windows 11 Home', '新品', 'LEADTIME', false, false, 117000, 117000, 'Ryzen 5 5500', 'Integrated', 'integrated', 2, false, 16, 512, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0GRJTNZRR', 'https://www.amazon.co.jp/dp/B0GRJTNZRR?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/51HB2u4E1rL._SL160_.jpg', '', '2026-06-20', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0GRJTNZRR%' OR af_url ILIKE '%B0GRJTNZRR%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'DARUMA', 'DARUMA-PCRyzen5 5500 / メモリ16GB / SSD 1TB M2 NVMe / B550M WiFi6+ Bluetooth/Windows 11 Home / 拡張可能650W Ryzen 5 5500', '新品', 'IN_STOCK', false, false, 185800, 185800, 'Ryzen 5 5500', 'RTX 5060', 'dgpu', 8, true, 16, 1024, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0G3L9Y88J', 'https://www.amazon.co.jp/dp/B0G3L9Y88J?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/51+iHKZjXbL._SL160_.jpg', '', '2026-06-20', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0G3L9Y88J%' OR af_url ILIKE '%B0G3L9Y88J%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'TITAN GAMING', 'TITAN GAMING ゲーミングPC デスクトップパソコン GeForce RTX 5060 Ti 16GB Ryzen 7 5700X メモリ32GB NVMe SSD 512GB Window', '新品', 'LEADTIME', false, false, 238000, 238000, 'Ryzen 7 5700X', 'RTX 5060', 'dgpu', 8, true, 32, 512, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0GT5X5YNH', 'https://www.amazon.co.jp/dp/B0GT5X5YNH?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/41dGrwe2I8L._SL160_.jpg', '', '2026-06-20', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0GT5X5YNH%' OR af_url ILIKE '%B0GT5X5YNH%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'マウスコンピューター(Mouse Computer)', 'マウスコンピューター(Mouse Computer) mouse  ゲーミングPC デスクトップPC G TUNE DG (Core i5 14400F 16GB メモリ 1TB SSD Windows 11 無線LAN ゲーム 動画編集) DGI5G6 Core i5-14400F', '新品', 'IN_STOCK_SCARCE', false, false, 299800, 299800, 'Core i5-14400F', 'RTX 5060', 'dgpu', 8, true, 16, 1024, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0GMPNDLCG', 'https://www.amazon.co.jp/dp/B0GMPNDLCG?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/419-R5IxJaL._SL160_.jpg', '', '2026-06-20', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0GMPNDLCG%' OR af_url ILIKE '%B0GMPNDLCG%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'TITAN GAMING', 'TITAN GAMING ゲーミングPC デスクトップパソコン GeForce RTX 5070 Ryzen 7 7800X3D メモリ32GB NVMe SSD 512GB Windows 11 H', '新品', 'LEADTIME', false, false, 314000, 314000, 'Ryzen 7 7800X3D', 'RTX 5070', 'dgpu', 9, true, 32, 512, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0GT5WPFW2', 'https://www.amazon.co.jp/dp/B0GT5WPFW2?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/41XEMz+923L._SL160_.jpg', '', '2026-06-20', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0GT5WPFW2%' OR af_url ILIKE '%B0GT5WPFW2%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'ASUS', 'ASUS ゲーミングデスクトップPC TUF Gaming TM500 TM500MH GeForce RTX 5050 AMD Ryzen 5 220 メモリ16GB SSD1TB Windows1', '新品', 'IN_STOCK_SCARCE', false, false, 184800, 184800, 'Ryzen 5 220', 'Integrated', 'integrated', 2, false, 16, 1024, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0GMPZ2T8H', 'https://www.amazon.co.jp/dp/B0GMPZ2T8H?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/4145ILO-rvL._SL160_.jpg', '', '2026-06-20', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0GMPZ2T8H%' OR af_url ILIKE '%B0GMPZ2T8H%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'ＧＡＬＬＥＲＩＡ', 'ＧＡＬＬＥＲＩＡ ガレリア ゲーミングPC  GALLERIA XPR7A-R56-GD Ryzen 7 7700搭載 Windows 11 Home 動画編集 ゲーム実況 19889-4816', '新品', 'LEADTIME', false, false, 291180, 291180, 'Ryzen 7 7700', 'RTX 5060', 'dgpu', 8, true, 16, 1024, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B00KG9KA5A', 'https://www.amazon.co.jp/dp/B00KG9KA5A?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/31yFYclu01L._SL160_.jpg', '', '2026-06-20', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B00KG9KA5A%' OR af_url ILIKE '%B00KG9KA5A%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'ASUS', 'ASUS ゲーミングPC ROG G700 GM700TZ GeForce RTX 5080 AMD Ryzen 7 9800X3D メモリ64GB SSD2TB Windows11 液冷CPUクーラ', '新品', 'IN_STOCK_SCARCE', false, false, 698000, 698000, 'Ryzen 7 9800X3D', 'RTX 5080', 'dgpu', 10, true, 64, 64, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0FDKL4F2Y', 'https://www.amazon.co.jp/dp/B0FDKL4F2Y?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/41lYCzXKCjL._SL160_.jpg', '', '2026-06-20', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0FDKL4F2Y%' OR af_url ILIKE '%B0FDKL4F2Y%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'WaffleMK', 'WaffleMK ゲーミングPC タワー型 G-StormXi Geforce RTX 5070 Core i9-13900F 32GBメモリ 2.0TBSSD WiFi Windows 11 クリエ', '新品', 'LEADTIME', false, false, 498800, 498800, 'Core i9-13900F', 'RTX 5070', 'dgpu', 9, true, 32, 2048, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0F2HD9TN1', 'https://www.amazon.co.jp/dp/B0F2HD9TN1?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/51AIOhiyFSL._SL160_.jpg', '', '2026-06-20', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0F2HD9TN1%' OR af_url ILIKE '%B0F2HD9TN1%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'WaffleMK', 'WaffleMK ゲーミングPC タワー型 G-Stormシリーズ AMD GeForce 16GBメモリ Windows 11 WPS Office2 SSD512GB Ryzen 5 5500 R', '新品', 'LEADTIME', false, false, 159500, 159500, 'Ryzen 5 5500', 'RTX 4060', 'dgpu', 7, true, 16, 512, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0DMRQBF6C', 'https://www.amazon.co.jp/dp/B0DMRQBF6C?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/41daOoCiiZL._SL160_.jpg', '', '2026-06-20', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0DMRQBF6C%' OR af_url ILIKE '%B0DMRQBF6C%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'WaffleMK', 'WaffleMK ゲーミングPC タワー型 G-Stormシリーズ AMD GeForce 16GBメモリ Windows 11 WPS Office2 SSD512GB Ryzen 5 4500 G', '新品', 'LEADTIME', false, false, 99800, 99800, 'Ryzen 5 4500', 'GTX 1650', 'dgpu', 3, true, 16, 512, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0CXHYN4QN', 'https://www.amazon.co.jp/dp/B0CXHYN4QN?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/41sp8aBpAaL._SL160_.jpg', '', '2026-06-20', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0CXHYN4QN%' OR af_url ILIKE '%B0CXHYN4QN%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'WaffleMK', 'WaffleMK ゲーミングPC タワー型 G-Stormシリーズ AMD GeForce 16GBメモリ Windows 11 WPS Office2 SSD1.0TB Ryzen 7 5700X', '新品', 'LEADTIME', false, false, 152800, 152800, 'Ryzen 7 5700X', 'Integrated', 'integrated', 2, false, 16, 1024, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0CXHYWP54', 'https://www.amazon.co.jp/dp/B0CXHYWP54?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/41fS0SKup1L._SL160_.jpg', '', '2026-06-20', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0CXHYWP54%' OR af_url ILIKE '%B0CXHYWP54%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'WaffleMK', 'WaffleMK ゲーミングPC タワー型 G-StormRシリーズ AMD Ryzen 5 4500 - GeForce RTX 3060 12G - 16GBメモリ - 500GB - WiFi', '新品', 'LEADTIME', false, false, 134800, 134800, 'Ryzen 5 4500', 'Integrated', 'integrated', 2, false, 16, 500, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0F1MFZTQS', 'https://www.amazon.co.jp/dp/B0F1MFZTQS?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/51sjpAKUnnL._SL160_.jpg', '', '2026-06-20', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0F1MFZTQS%' OR af_url ILIKE '%B0F1MFZTQS%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'Dell', 'Dell デスクトップパソコン Dell Tower ECT1250 Core Ultra 7 265 メモリ32GB SSD 1TB Windows 11 Home ブラック (2025春モデル)', '新品', 'IN_STOCK_SCARCE', false, false, 200000, 200000, 'Core Ultra 7 265', 'Integrated', 'integrated', 2, false, 32, 1024, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0F4Q12C35', 'https://www.amazon.co.jp/dp/B0F4Q12C35?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/41zILYeIuTL._SL160_.jpg', '', '2026-06-20', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0F4Q12C35%' OR af_url ILIKE '%B0F4Q12C35%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'Dell', 'Dell デスクトップパソコン Dell Tower ECT1250 Core i7 14700 メモリ16GB SSD 1TB Windows 11 Pro ブラック (2025春モデル) Core i7-14700', '新品', 'LEADTIME', false, false, 278522, 278522, 'Core i7-14700', 'Integrated', 'integrated', 2, false, 16, 1024, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0F4PYHKXX', 'https://www.amazon.co.jp/dp/B0F4PYHKXX?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/41zILYeIuTL._SL160_.jpg', '', '2026-06-20', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0F4PYHKXX%' OR af_url ILIKE '%B0F4PYHKXX%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'ＮＥＷＬＥＡＧＵＥ', 'ＮＥＷＬＥＡＧＵＥ NEWLEAGUE ゲーミングデスクトップパソコン 特選モデルRyzen 5 5500 / RTX3050 / 16GB / NVMe SSD 512GB / 550W電源ユニット / Windows', '新品', 'LEADTIME', false, false, 149800, 149800, 'Ryzen 5 5500', 'Integrated', 'integrated', 2, false, 50, 512, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0CX58FRQH', 'https://www.amazon.co.jp/dp/B0CX58FRQH?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/41Gq3tWJ4BL._SL160_.jpg', '', '2026-06-20', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0CX58FRQH%' OR af_url ILIKE '%B0CX58FRQH%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'Dell', 'Dell デスクトップパソコン Dell Tower ECT1250 Core i5 14400 メモリ16GB SSD 512GB Windows 11 Home ブラック Microsoft Of Core i5-14400', '新品', 'IN_STOCK_SCARCE', false, false, 209800, 209800, 'Core i5-14400', 'Integrated', 'integrated', 2, false, 16, 512, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0F4R9YLNJ', 'https://www.amazon.co.jp/dp/B0F4R9YLNJ?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/41zILYeIuTL._SL160_.jpg', '', '2026-06-20', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0F4R9YLNJ%' OR af_url ILIKE '%B0F4R9YLNJ%'));

COMMIT;
