-- Specsy desktop-pc product INSERT SQL generated on 2026-06-19
-- Review candidates before running this in Supabase SQL Editor.
BEGIN;

ALTER TABLE am_pc_data ADD COLUMN IF NOT EXISTS condition_label text;
ALTER TABLE am_pc_data ADD COLUMN IF NOT EXISTS availability text;
ALTER TABLE am_pc_data ADD COLUMN IF NOT EXISTS is_used boolean DEFAULT false;
ALTER TABLE am_pc_data ADD COLUMN IF NOT EXISTS is_refurbished boolean DEFAULT false;
ALTER TABLE am_pc_data ADD COLUMN IF NOT EXISTS gpu text;
ALTER TABLE am_pc_data ADD COLUMN IF NOT EXISTS gpu_class text;
ALTER TABLE am_pc_data ADD COLUMN IF NOT EXISTS gpu_score integer;
ALTER TABLE am_pc_data ADD COLUMN IF NOT EXISTS has_dgpu boolean DEFAULT false;

INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'Dobios', 'Dobios 22インチ 液晶一体型 デスクトップパソコン 第2世代 Core i5 Windows 11搭載 MS Office2019搭載 一体型pc USB 2.0/無線LAN/Bluetooth/キーボード', '新品', 'IN_STOCK_SCARCE', false, false, 42800, 42800, 'Core i5', 'Integrated', 'integrated', 2, false, 8, 256, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0C2PYPLCR', 'https://www.amazon.co.jp/dp/B0C2PYPLCR?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/51FpwHGrwQL._SL160_.jpg', '', '2026-06-19', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0C2PYPLCR%' OR af_url ILIKE '%B0C2PYPLCR%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'TITAN GAMING', 'TITAN GAMING ゲーミングPC デスクトップパソコン GeForce RTX 5060 Ti 8GB Ryzen 7 5700X メモリ16GB NVMe SSD 512GB Windows', '新品', 'LEADTIME', false, false, 183000, 183000, 'Ryzen 7 5700X', 'RTX 5060', 'dgpu', 8, true, 16, 512, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0GRJGH6LH', 'https://www.amazon.co.jp/dp/B0GRJGH6LH?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/41XEMz+923L._SL160_.jpg', '', '2026-06-19', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0GRJGH6LH%' OR af_url ILIKE '%B0GRJGH6LH%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'VETESA', 'VETESA デスクトップパソコン 27インチ 一体型パソコン 高性能Core i7 IPS 液晶・多機能一体型PC 16GB 512GB SSD 初期設定済み Office 2024付き Windo', '新品', 'IN_STOCK_SCARCE', false, false, 74800, 74800, 'Core i7', 'Integrated', 'integrated', 2, false, 16, 512, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0GZVT8ZB2', 'https://www.amazon.co.jp/dp/B0GZVT8ZB2?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/51OdUVe6ypL._SL160_.jpg', '', '2026-06-19', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0GZVT8ZB2%' OR af_url ILIKE '%B0GZVT8ZB2%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'DARUMA', 'DARUMA-PC デスクトップPC (Ryzen5 5500GT / 16GB メモリ/ 500GB SSD/DVI+ HDMI+ VGA/Windows 11 HOME Wi-Fi Ryzen 5 5500GT', '新品', 'IN_STOCK_SCARCE', false, false, 79800, 79800, 'Ryzen 5 5500GT', 'Integrated', 'integrated', 2, false, 16, 500, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0GH7F9QXB', 'https://www.amazon.co.jp/dp/B0GH7F9QXB?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/31ca1VWRXML._SL160_.jpg', '', '2026-06-19', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0GH7F9QXB%' OR af_url ILIKE '%B0GH7F9QXB%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'SOOYA', 'SOOYA デスクトップパソコン一体型 SOOYA 22インチ Core i5 第2世代 Windows11Pro Office付きノートパソコン office2024へ変更可 フルHD1920*1080P IP', '新品', 'IN_STOCK_SCARCE', false, false, 41800, 41800, 'Core i5', 'Integrated', 'integrated', 2, false, 8, 256, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0G18PFV8V', 'https://www.amazon.co.jp/dp/B0G18PFV8V?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/511BytUModL._SL160_.jpg', '', '2026-06-19', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0G18PFV8V%' OR af_url ILIKE '%B0G18PFV8V%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'AAYB', 'AAYB デスクトップパソコン/NEC Mate デスクトップPC / 第10世代 Core i5 / メモリ16GB / SSD 256GB / Windows 11 / Office 2021 / 省スペー', '新品', 'IN_STOCK_SCARCE', false, false, 43980, 43980, 'Core i5', 'Integrated', 'integrated', 2, false, 16, 256, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0H3V947MT', 'https://www.amazon.co.jp/dp/B0H3V947MT?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/41lEaXTEdLL._SL160_.jpg', '', '2026-06-19', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0H3V947MT%' OR af_url ILIKE '%B0H3V947MT%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'TITAN GAMING', 'TITAN GAMING ゲーミングPC デスクトップパソコン GeForce RTX 5060 Ryzen 7 5700X メモリ32GB NVMe SSD 1TB Windows 11 Home', '新品', 'LEADTIME', false, false, 199000, 199000, 'Ryzen 7 5700X', 'RTX 5060', 'dgpu', 8, true, 32, 1024, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0H1CC5K7L', 'https://www.amazon.co.jp/dp/B0H1CC5K7L?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/4131w7atndL._SL160_.jpg', '', '2026-06-19', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0H1CC5K7L%' OR af_url ILIKE '%B0H1CC5K7L%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'DARUMA', 'DARUMA-PC デスクトップPC Ryzen 5 / 16GB メモリ/ M2 NVMe SSD 256GB / DVI+ HDMI+ VGA/Windows 11 HOME Wi-Fi ，Rad Ryzen 5 3400G', '新品', 'IN_STOCK_SCARCE', false, false, 59800, 59800, 'Ryzen 5 3400G', 'Integrated', 'integrated', 2, false, 16, 256, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0GM67P8SQ', 'https://www.amazon.co.jp/dp/B0GM67P8SQ?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/31fPyZdJLHL._SL160_.jpg', '', '2026-06-19', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0GM67P8SQ%' OR af_url ILIKE '%B0GM67P8SQ%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'Dell', 'Dell デスクトップパソコン 一体型 Dell 24 AIO EC24250 23.8インチ Core i5-1334U メモリ16GB SSD512GB Windows 11 パールホワイト 翌営', '新品', 'IN_STOCK_SCARCE', false, false, 190980, 190980, 'Core i5-1334U', 'Integrated', 'integrated', 2, false, 16, 512, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0F4JWJ4LG', 'https://www.amazon.co.jp/dp/B0F4JWJ4LG?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/41p8V2PChqL._SL160_.jpg', '', '2026-06-19', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0F4JWJ4LG%' OR af_url ILIKE '%B0F4JWJ4LG%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'マウスコンピューター(Mouse Computer)', 'マウスコンピューター(Mouse Computer) mouse  ゲーミングPC デスクトップPC G TUNE DG (Core i5 14400F 16GB メモリ 1TB SSD Windows 11 無線LAN ゲーム 動画編集) DGI5G6 Core i5-14400F', '新品', 'IN_STOCK_SCARCE', false, false, 299800, 299800, 'Core i5-14400F', 'RTX 5060', 'dgpu', 8, true, 16, 1024, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0GMPNDLCG', 'https://www.amazon.co.jp/dp/B0GMPNDLCG?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/419-R5IxJaL._SL160_.jpg', '', '2026-06-19', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0GMPNDLCG%' OR af_url ILIKE '%B0GMPNDLCG%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'TITAN GAMING', 'TITAN GAMING ゲーミングPC デスクトップパソコン GeForce RTX 3050 Ryzen 7 5700X メモリ32GB NVMe SSD 1TB Windows 11 Home', '新品', 'LEADTIME', false, false, 156000, 156000, 'Ryzen 7 5700X', 'Integrated', 'integrated', 2, false, 32, 1024, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0H1CJJNCF', 'https://www.amazon.co.jp/dp/B0H1CJJNCF?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/31fUtzEIA6L._SL160_.jpg', '', '2026-06-19', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0H1CJJNCF%' OR af_url ILIKE '%B0H1CJJNCF%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'UFOREST', 'UFOREST DARUMAPC (ダルマPC） No.1 デスクトップパソコン コスパ 最高 WiFi (i5-14400 | RAM16GB | SSD500GB | Win11Pro64bit/ OfficeP Core i5-14400', '新品', 'IN_STOCK', false, false, 105400, 105400, 'Core i5-14400', 'Integrated', 'integrated', 2, false, 16, 500, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0C1TVL66T', 'https://www.amazon.co.jp/dp/B0C1TVL66T?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/411GurP9T0L._SL160_.jpg', '', '2026-06-19', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0C1TVL66T%' OR af_url ILIKE '%B0C1TVL66T%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'ＮＥＷＬＥＡＧＵＥ', 'ＮＥＷＬＥＡＧＵＥ NEWLEAGUE デスクトップPC, Core i5 14400搭載, 16GBメモリ, 512GB SSD, Windows11 Pro, WPS Office, WIFI子機無償プレゼント, ス Core i5-14400', '新品', 'IN_STOCK_SCARCE', false, false, 99800, 99800, 'Core i5-14400', 'Integrated', 'integrated', 2, false, 16, 512, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0F28KWT5P', 'https://www.amazon.co.jp/dp/B0F28KWT5P?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/31w7wcxzFKL._SL160_.jpg', '', '2026-06-19', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0F28KWT5P%' OR af_url ILIKE '%B0F28KWT5P%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'ＮＥＷＬＥＡＧＵＥ', 'ＮＥＷＬＥＡＧＵＥ NEWLEAGUE デスクトップPC, Core i5 14400搭載, 32GBメモリ, 1TB SSD, Win11 pro, WPS Office, WIFI子機無償プレゼント, スリムタワー型 Core i5-14400', '新品', 'IN_STOCK_SCARCE', false, false, 129800, 129800, 'Core i5-14400', 'Integrated', 'integrated', 2, false, 32, 1024, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0F28LRMPW', 'https://www.amazon.co.jp/dp/B0F28LRMPW?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/31w7wcxzFKL._SL160_.jpg', '', '2026-06-19', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0F28LRMPW%' OR af_url ILIKE '%B0F28LRMPW%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'DARUMA', 'DARUMA-PC デスクトップPC Core i5 14400 / 16GB メモリ/ 500GB SSD/HDMI/Windows 11 Pro/MS 2021 Wi-Fi 6 Core i5-14400', '新品', 'IN_STOCK', false, false, 99800, 99800, 'Core i5-14400', 'Integrated', 'integrated', 2, false, 16, 500, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0GM62V8K8', 'https://www.amazon.co.jp/dp/B0GM62V8K8?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/31fPyZdJLHL._SL160_.jpg', '', '2026-06-19', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0GM62V8K8%' OR af_url ILIKE '%B0GM62V8K8%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'ＮＥＷＬＥＡＧＵＥ', 'ＮＥＷＬＥＡＧＵＥ NEWLEAGUE デスクトップPC, Core i5 14400搭載, 32GBメモリ, 2TB SSD, Win11 pro, WPS Office, WIFI子機無償プレゼント, スリムタワー型 Core i5-14400', '新品', 'IN_STOCK_SCARCE', false, false, 149800, 149800, 'Core i5-14400', 'Integrated', 'integrated', 2, false, 32, 2048, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0F28LNNF5', 'https://www.amazon.co.jp/dp/B0F28LNNF5?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/31w7wcxzFKL._SL160_.jpg', '', '2026-06-19', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0F28LNNF5%' OR af_url ILIKE '%B0F28LNNF5%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'DARUMA', 'DARUMA-PC デスクトップPCCore i5 14400 / メモリ32GB / SSD 1TB M2 NVMe Gen 4/ Windows 11 Pro & Office 2021 / DV Core i5-14400', '新品', 'IN_STOCK', false, false, 129800, 129800, 'Core i5-14400', 'RTX 4060', 'dgpu', 7, true, 32, 1024, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0D5MFBVSY', 'https://www.amazon.co.jp/dp/B0D5MFBVSY?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/41JKgQrX-kL._SL160_.jpg', '', '2026-06-19', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0D5MFBVSY%' OR af_url ILIKE '%B0D5MFBVSY%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'Dell', 'Dell デスクトップパソコン Dell Slim ECS1250 Core i5 14400 メモリ8GB SSD 512GB Windows 11 Home ブラック (2025春モデル) Core i5-14400', '新品', 'LEADTIME', false, false, 163942, 163942, 'Core i5-14400', 'Integrated', 'integrated', 2, false, 8, 512, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0F4PYB64C', 'https://www.amazon.co.jp/dp/B0F4PYB64C?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/41hdCa9MN7L._SL160_.jpg', '', '2026-06-19', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0F4PYB64C%' OR af_url ILIKE '%B0F4PYB64C%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'DARUMA', 'DARUMA-PC デスクトップPC Core i5 14400 / 16GB メモリ/ 500GB SSD/HDMI/Windows 11 HOME Wi-Fi 6 Bluetooth Core i5-14400', '新品', 'IN_STOCK_SCARCE', false, false, 92800, 92800, 'Core i5-14400', 'Integrated', 'integrated', 2, false, 16, 500, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0GM677W3F', 'https://www.amazon.co.jp/dp/B0GM677W3F?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/31fPyZdJLHL._SL160_.jpg', '', '2026-06-19', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0GM677W3F%' OR af_url ILIKE '%B0GM677W3F%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'Dell', 'Dell デスクトップパソコン Dell Slim ECS1250 Core i5-14400 メモリ16GB SSD512GB Windows 11 ブラック 翌営業日対応オンサイト出張修理サービス', '新品', 'IN_STOCK', false, false, 150980, 150980, 'Core i5-14400', 'Integrated', 'integrated', 2, false, 16, 512, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0F4JVSMJT', 'https://www.amazon.co.jp/dp/B0F4JVSMJT?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/31WwC1ygT2L._SL160_.jpg', '', '2026-06-19', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0F4JVSMJT%' OR af_url ILIKE '%B0F4JVSMJT%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'Lenovo', 'Lenovo レノボ ThinkCentre Neo 50s Small Gen 4 Windows11 Pro Core i5 メモリ 16GB SSD 512GB DVDスーパーマルチ VGA D Core i5-12400', '新品', 'IN_STOCK', false, false, 139980, 139980, 'Core i5-12400', 'Integrated', 'integrated', 2, false, 16, 512, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0GX8D2HKS', 'https://www.amazon.co.jp/dp/B0GX8D2HKS?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/41dUN+0ab0L._SL160_.jpg', '', '2026-06-19', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0GX8D2HKS%' OR af_url ILIKE '%B0GX8D2HKS%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'ＮＥＷＬＥＡＧＵＥ', 'ＮＥＷＬＥＡＧＵＥ NEWLEAGUE デスクトップPC, Core i5 14400搭載, 16GBメモリ, 512GB SSD, Win11 pro,Office 2021搭載,スリムタワー型 (V1ブラック, 51 Core i5-14400', '新品', 'IN_STOCK_SCARCE', false, false, 139800, 139800, 'Core i5-14400', 'Integrated', 'integrated', 2, false, 16, 512, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0F32KDCZD', 'https://www.amazon.co.jp/dp/B0F32KDCZD?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/31w7wcxzFKL._SL160_.jpg', '', '2026-06-19', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0F32KDCZD%' OR af_url ILIKE '%B0F32KDCZD%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'ＮＥＷＬＥＡＧＵＥ', 'ＮＥＷＬＥＡＧＵＥ ゲーミングパソコン Ryzen 5 5600G / メモリ16GB / NVMe SSD 512GB / Windows11Pro / WPS Office ミドルタワー デスクトップパソコン (Ry', '新品', 'IN_STOCK_SCARCE', false, false, 95800, 95800, 'Ryzen 5 5600G', 'Integrated', 'integrated', 2, false, 16, 512, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B09RPTMPZ3', 'https://www.amazon.co.jp/dp/B09RPTMPZ3?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/41t+tXZmx0L._SL160_.jpg', '', '2026-06-19', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B09RPTMPZ3%' OR af_url ILIKE '%B09RPTMPZ3%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'Generic', 'Generic PC-TECH デスクトップパソコン Ryzen 5 3400G / メモリー16GB / 高速&大容量 M.2 NvMe SSD 1TB / Radeon™ RX Vega 11 Graphics', '新品', 'LEADTIME', false, false, 89980, 89980, 'Ryzen 5 3400G', 'Integrated', 'integrated', 2, false, 16, 1024, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0GTZ8S27N', 'https://www.amazon.co.jp/dp/B0GTZ8S27N?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/31rNy++VkEL._SL160_.jpg', '', '2026-06-19', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0GTZ8S27N%' OR af_url ILIKE '%B0GTZ8S27N%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'HP', 'HP デスクトップPC タワー型 OmniDesk AMD Ryzen 5 8500G プロセッサー 16GBメモリ 1TB SSD Windows11 Home (型番：B87KYPA-AAAA)', '新品', 'LEADTIME', false, false, 149800, 149800, 'Ryzen 5 8500G', 'Integrated', 'integrated', 2, false, 16, 1024, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0DZ5X9H8G', 'https://www.amazon.co.jp/dp/B0DZ5X9H8G?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/31WavdKe9cL._SL160_.jpg', '', '2026-06-19', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0DZ5X9H8G%' OR af_url ILIKE '%B0DZ5X9H8G%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'DARUMA', 'DARUMA-PC デスクトップPC Ryzen 5, 16GB メモリ/ M2 NVMe SSD 256GB / DVI+ HDMI+ VGA/Windows 11 Pro/MS 2021 Wi-F Ryzen 5 3400G', '新品', 'IN_STOCK_SCARCE', false, false, 78800, 78800, 'Ryzen 5 3400G', 'Integrated', 'integrated', 2, false, 16, 256, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0GM62L57Q', 'https://www.amazon.co.jp/dp/B0GM62L57Q?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/31fPyZdJLHL._SL160_.jpg', '', '2026-06-19', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0GM62L57Q%' OR af_url ILIKE '%B0GM62L57Q%'));
INSERT INTO am_pc_data (id, form_factor, display_size, brand, name, condition_label, availability, is_used, is_refurbished, price, real_price, cpu, gpu, gpu_class, gpu_score, has_dgpu, ram, rom, battery, battery_wh_normalized, weight, url, af_url, img_url, imp_img_url, fetched_at, is_active)
SELECT (SELECT COALESCE(MAX(id), 0) + 1 FROM am_pc_data), 'Desktop', NULL, 'Generic', 'Generic PC-TECH ゲーミングデスクトップパソコン Ryzen 5 5500 / RTX 5060Ti / メモリー32GB / 高速&大容量 M.2 NvMe SSD 1TB / B550M / Win', '新品', 'LEADTIME', false, false, 205000, 205000, 'Ryzen 5 5500', 'RTX 5060', 'dgpu', 8, true, 32, 1024, '', NULL, NULL, 'https://www.amazon.co.jp/dp/B0GVS1Y79B', 'https://www.amazon.co.jp/dp/B0GVS1Y79B?tag=nmsuteado2-22&linkCode=osi&th=1&psc=1', 'https://m.media-amazon.com/images/I/31rNy++VkEL._SL160_.jpg', '', '2026-06-19', true
WHERE NOT EXISTS (SELECT 1 FROM am_pc_data WHERE (url ILIKE '%B0GVS1Y79B%' OR af_url ILIKE '%B0GVS1Y79B%'));

COMMIT;
